CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(16) NOT NULL,
    lastName VARCHAR(25) NOT NULL,
    birthdate DATE NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);